# DataSource Config
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://182.92.2.76:3306/sbtream?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 666666