# DataSource Config
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.33.10:3306/sbtream?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 666666

