server:
  port: 31407

#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: com.borber.sbtream.server.model.entity

#配置控制台打印日志Debug
logging:
  level:
    com.borber.sbtream: debug

sbtream:
  plugin:
    path: plugins
  data:
    json:
      setting: json/setting.json


